version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service-backend
    ports:
      - "8081:8081"
    depends_on:
      auth-mysql:
        condition: service_healthy
    env_file:
      - .env

  auth-mysql:
    image: mysql:8.0
    restart: always
    container_name: auth-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST : "auth-mysql"
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PORT : ${MYSQL_PORT}
      MYSQL_PASSWORD : ${MYSQL_PASS}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    ports:
      - "3307:3306"
    volumes:
      - auth-db-data:/var/lib/mysql
volumes:
  auth-db-data:
